---
kind: application
name: devbox
network:
    external: [5050]
deployment_defaults:
    new:
        image:
            kube_test: ubunutu-16.01
            aws_stage: amixx
configuration:
    run_script: 
            kube_test: config_kube.sh
            aws_stage: config_aws.sh


